# Use postgres/example user/password credentials
version: '3.9'

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
volumes:
  postgres-data: